# Generated by Django 3.0.4 on 2020-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20200322_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularexam',
            name='exam_name',
        ),
    ]
