# Generated by Django 3.0.4 on 2020-03-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_regularexam_some_five'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regularexam',
            old_name='some_five',
            new_name='sum_five',
        ),
    ]
