# Generated by Django 3.0.4 on 2020-03-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20200322_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('term_name', models.CharField(max_length=10)),
            ],
        ),
    ]
