# Generated by Django 3.0.4 on 2020-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_recordgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeIdLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('start_id', models.IntegerField()),
            ],
        ),
    ]
