# Generated by Django 3.0.4 on 2020-03-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_auto_20200328_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceexam',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.PracticeMonth'),
        ),
        migrations.AlterField(
            model_name='regularexam',
            name='regular_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.RegularExamGroup'),
        ),
    ]
