# Generated by Django 3.0.4 on 2020-03-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20200328_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeidlink',
            name='birth_year',
            field=models.IntegerField(default=2005),
            preserve_default=False,
        ),
    ]
