# Generated by Django 3.0.4 on 2020-05-03 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_gradeidlink_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelimit',
            name='limit_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
