# Generated by Django 3.0.4 on 2020-03-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementarySchool',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JuniorHighSchool',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('name_ruby', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('home_room', models.CharField(max_length=10, null=True)),
                ('local_school', models.CharField(max_length=10, null=True)),
                ('entry_grade', models.CharField(max_length=10, null=True)),
                ('birthday', models.DateField(null=True)),
                ('club', models.CharField(max_length=10, null=True)),
                ('parents', models.CharField(max_length=10, null=True)),
                ('siblings', models.CharField(max_length=10, null=True)),
                ('info', models.TextField(null=True)),
            ],
        ),
    ]
