# Generated by Django 3.0.4 on 2020-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='info',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
