# Generated by Django 3.0.4 on 2020-03-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200317_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementaryschool',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='juniorhighschool',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='juniorhighschool',
            name='term',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='club',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_ruby',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='siblings',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
