# Generated by Django 3.0.4 on 2020-03-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200318_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRoom',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
