# Generated by Django 3.0.4 on 2020-03-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_futurepath_privatehighschool_publichighschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatehighschool',
            name='add_point',
        ),
    ]
