# Generated by Django 3.0.4 on 2020-03-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_privatehighschool_add_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publichighschool',
            old_name='school_report_last_year',
            new_name='school_record_last_year',
        ),
        migrations.RenameField(
            model_name='publichighschool',
            old_name='school_report_this_year',
            new_name='school_record_this_year',
        ),
        migrations.RenameField(
            model_name='publichighschool',
            old_name='school_report_three_years_ago',
            new_name='school_record_three_years_ago',
        ),
    ]
