# Generated by Django 3.0.4 on 2020-04-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200328_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurepath',
            name='first_choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='first', to='student.PublicHighSchool'),
        ),
        migrations.AlterField(
            model_name='futurepath',
            name='private_school1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='first', to='student.PrivateHighSchool'),
        ),
        migrations.AlterField(
            model_name='futurepath',
            name='private_school2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='second', to='student.PrivateHighSchool'),
        ),
        migrations.AlterField(
            model_name='futurepath',
            name='private_school3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='third', to='student.PrivateHighSchool'),
        ),
        migrations.AlterField(
            model_name='futurepath',
            name='second_choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='second', to='student.PublicHighSchool'),
        ),
        migrations.AlterField(
            model_name='futurepath',
            name='third_choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='third', to='student.PublicHighSchool'),
        ),
    ]
