# Generated by Django 3.0.4 on 2020-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zenken',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zenken_number', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('enrollment', models.CharField(max_length=5, null=True)),
                ('prefecture', models.CharField(max_length=5, null=True)),
                ('city', models.CharField(max_length=5, null=True)),
                ('recordTerm', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
